### ISSUE TITLE
Merge your modifications to my repository?

### ISSUE THREAD

**Issue by RQWorldblender** [ssbucarlos/blender_io_nuanmb#1]
This is me from the author of the original repository, https://gitlab.com/Worldblender/io_scene_numdlb. I just noticed this repository and thought that it would be better to have your contributions merged into mine. Unless you have a good reason to not merge your contributions into mine, would you like to do a merge with my original repository?
You have to fork either the original GitLab repository or its mirror at https://github.com/RQWorldblender/io_scene_numdlb (the GitLab repository is preferred, so that I can record the contributions there), rebase your changes on top of mine, push to your fork, and make a merge request or pull request. I will handle the rest from there.

**Comment by ssbucarlos** [comment]
Sure, ill merge the importer changes when i get the chance

**Comment by RQWorldblender** [comment]
I just merged your changes into my repository; thank you for your contributions! After this, do you still want to keep this repository around, or just direct people to mine?

**Comment by ssbucarlos** [comment]
I plan to expand this project, so ill continue making changes here and direct ppl here for them. I wont make changes to the model.numdlb importer (thx btw its been a huge help having those scripts), which is a requirement of this script so ppl will still be directed to your repository anyways and download it from there. Ill make some PRs to your repository once i have some stable improvements to the nuanmb importer/exporter
