### ISSUE TITLE
Could you help us?

### ISSUE THREAD

**Issue by Showdown1234** [ssbucarlos/blender_io_nuanmb#3]
Hello, I tried to contact you but I did not have an answer, my idea is this I wanted you to help us modify your script since we want to export Ultimate animations but in this case we do not want it to be one by one but in batches or the entire folder, help us Or else guide us to be able to advance our project faster

Do you speak Spanish?

https://discord.gg/Dv5Fnx6DKM

**Comment by ssbucarlos** [comment]
Hi I see now that you tried contacting me on twitter but the message just said 'Hi' so I originally thought it might have been spam, sorry! I do speak Spanish, so feel free to leave messages in Spanish. At the moment I am not available to implement batch exporting or provide assistance on doing so. I simply don't know enough about how to go about doing it myself, which means I also don't know how to provide any assistance on implementing it... Sorry! I may eventually revisit the feature once I learn more about Blender scripting

**Comment by Showdown1234** [comment]
otra pregunta es, en que parte del script es donde se decodifican las animaciones porque queremos tambien exportar las animaciones faciales, en blender se muestra pero en Unity no

**Comment by ssbucarlos** [comment]
Los animaciones de smash tienen diferentes tipos de 'Tracks' en el archivo. Ay los 'Transform' tracks para los huesos, los 'Visibility' tracks que controlan la visibilidad de los meshes (el uso mas común es para controlar cual cara debería ser visible), los 'Material' tracks para cambiar propiedades de materiales. Los UVs de lo ojos se manipulan con cambios a 'Custom Vector 31' en el material track. Este script toma los valores de 'Custom Vector 31' y los pone en un Driver para controlar los UVs de los ojos en blender. Entonces, es algo muy particular a animaciones de smash entonces no se como se va poder exportar a Unity.

**Comment by ssbucarlos** [comment]
En el otro comentario solo explique lo de los ojos (Material Track). Preguntabas sobre los animaciones faciales (Visibility Track), y el concepto es similar a lo que dije de los ojos. La información de la visibilidad se decodifica y luego se meten keyframes que controlan la visibilidad de los meshes en blender. Como lo tengo entendido, no hay formato de animación común (fbx, dae, smd, etc.) que me deja meter esta información especial.

**Comment by Showdown1234** [comment]
> En el otro comentario solo explique lo de los ojos (Material Track). Preguntabas sobre los animaciones faciales (Visibility Track), y el concepto es similar a lo que dije de los ojos. La información de la visibilidad se decodifica y luego se meten keyframes que controlan la visibilidad de los meshes en blender. Como lo tengo entendido, no hay formato de animación común (fbx, dae, smd, etc.) que me deja meter esta información especial.

En el formato de las animaciones de unity se puede meter cualquier propiedad de un objeto. esto incluye la visibilidad sobre sus mesh y las uv de los materiales.

el plan por ahora seria poder leer esos keyframes de las animaciones de smash. en unity seria hacer un script que agregue todos esos keyframes a las animaciones

**Comment by ssbucarlos** [comment]
No tengo cualquier plan de crear el script, pero si lo fuera a crear, yo pienso que la mejor manera de hacerlo seria esperar que se completen uno de estos dos proyectos y usar los ( https://github.com/ScanMountGoat/ssbh_data_py o https://github.com/ultimate-research/ssbh_lib) para leer el .NUANMB directamente sin necesitar crear el parser como lo tengo en este script. Por ejemplo, puedes usar el ssbh_lib_json que viene incluido en el proyecto ssbh_data_py para leer el .NUANMB y sacar la información a un archivo .JSON. Ya teniendo el JSON con la informacion es mas facil hacer lo que tienes que hacer en unity o blender o cualquier otra programa. Pero en este momento, creo que esos dos proyectos no pueden uncompress los animaciones adentro de .NUANMB, entonces ay que esperar or si lo necesitas ahorita entonces puedes mas o menos copiar el parser que tengo en este script.
