### ISSUE TITLE
[Feature request] Pokemon Snap animation support

### ISSUE THREAD

**Issue by MagicMimi** [ssbucarlos/blender_io_nuanmb#4]
Hello !
First of all thanks a lot for your hard work on the plugin, thanks to you and other contributors I was able to study this wonderful smash bros animations :)

I was wondering if it could be possible to add support for Pokemon Snap nuanmb animations, they unfortunately don't seem to work for now but maybe the changes required are minimal, I'm unfortunately not a coder myself so I'm not sure.
Let me know if you need samples !
Once again thanks a lot for your work, hope you'll have a great week !

**Comment by ssbucarlos** [comment]
Hello! I briefly did check out the new pokemon snap .nuanmbs and it looks like the structure is different. Tbh im not sure how difficult it would be to parse and support the new format, but just from a quick look it appears that non-trivial changes would be required. Hopefully someone can come around and dedicate the time to figure it out!

**Comment by MagicMimi** [comment]
Thank you for answering, I understand !
A friend actually found out this tweet that got in their timeline, I discovered it after posting the issue : https://twitter.com/joschimy/status/1400383441175298048
So it seems that there are some tools to extract them but I didn't manage to find them. I tried to contact the poster by no answer yet :/
Do you know them by any chance ? I tried asking the drp extractor author but he has no clue either.
